flags:
	gcc tests/flags.c ../components/control_unit.c -I ../headers
	./cmp.sh answers/flags
	rm a.out
fsm:
	gcc tests/fsm.c ../components/control_unit.c -I ../headers
	./cmp.sh answers/fsm
	rm a.out
